pivnet_token:
opsman_major_minor_version_2_1:
ert_major_minor_version_2_1:
opsman_major_minor_version_2_0:
ert_major_minor_version_2_0:
stemcell_version:
s3_access_key_id:
s3_secret_access_key:
s3_endpoint:
s3_bucket:

isolation_segment_major_minor_version:
redis_major_minor_version:
rabbitmq_major_minor_version:
spring_cloud_services_major_minor_version:
mysql_major_minor_version:
mysql_2_0_major_minor_version:
healthwatch_major_minor_version:
dataflow_major_minor_version:
single_sign_on_major_minor_version: