pivnet_token: ((pivnet_token)) # [R] PivNet Access Token
github_token: ((github_token)) # [R] Your github token
github_repo: https://github.com/rahul-kj/pcf-concourse-pipelines # [R] Pipelines github repo
github_branch: master

product_s3_regex: "p-msql/p-mysql.(.*).tgz"
stemcell_s3_regexp: "stemcells/3445/bosh-stemcell-(.*)-.*.tgz"

iaas_type: vsphere

debug: false  # Set to true if you want to see all the tasks output. This will also show all the secrets and certs, so think twice

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr))  # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd))  # [R] Ops Manager admin password

product_name: p-mysql
product_identifier: p-mysql
product_version: ^1\.10\..*$

singleton_jobs_az:
other_azs:
network_name:

isolation_segment_domains: "[\"*.cfis.example.com\",\"*.cfis.example1.com\"]"
container_networking: enable # enable|disable
enable_grootfs: true # true|false
garden_disk_cleanup: "threshold" # never|routine|threshold
gorouter_ssl_ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
haproxy_forward_tls: disable # enable|disable
backend_ca: ""
haproxy_max_buffer_size: 16384
haproxy_ssl_ciphers: "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
networking_poe_ssl_name: ""
networking_poe_ssl_cert_pem: ""
networking_poe_ssl_cert_private_key_pem: ""
networking_point_of_entry: terminate_at_router
nfs_volume_driver: disable # enable|disable
ldap_server_host: ""
ldap_server_port: ""
ldap_service_account_password: ""
ldap_service_account_user: ""
ldap_user_fqdn: ""
router_backend_max_conn: 500
router_client_cert_validation: request # none|request|require
routing_custom_ca_certificates: ""
routing_disable_http: false # true|false
routing_minimum_tls_version: tls_v1_2 # tls_v1_0|tls_v1_1|tls_v1_2
routing_table_sharding_mode: isolation_segment_only # isolation_segment_only|no_isolation_segment
routing_tls_termination: load_balancer # load_balancer|ha_proxy|router
skip_cert_verify: true # true|false
system_logging: disabled # enabled|disabled
syslog_host: ""
syslog_port: ""
suslog_protocol: ""
syslog_rule: ""
syslog_tls_ca_cert: ""
syslog_tls_enabled: false # true|false
syslog_tls_permitted_peer: ""
syslog_use_tcp_for_file_forwarding_local_transport: false # true|false
ha_proxy_static_ips: ""
internal_only_domains: ""
trusted_domain_cidrs: ""
router_static_ips: ""
disable_insecure_cookies: false # true|false
enable_zipkin: true # true|false
enable_write_access_logs: true # true|false
request_timeout_in_seconds: 900
max_idle_connections: 0
extra_headers_to_log: ""
drain_wait: 20
lb_healthy_threshold: 20
executor_disk_capacity: ""
executor_memory_capacity: ""
insecure_docker_registry_list: ""
placement_tag: CHANGEME

isolated_ha_proxy_instances: 3
isolated_router_instances: 3
isolated_diego_cell_instances: 3

errands_to_disable: "broker-registrar,smoke-tests"

concourse_url: ((concourse_url))
concourse_user: ((concourse_user))
concourse_pwd: ((concourse_pwd))

pipeline-name: install-mysql
team-name: ((team-name))
upgrade-pipeline-name: upgrade-mysql